### ISSUE TITLE
SDK crashes when `sendRequest` is called without `connect` 

### ISSUE THREAD

**Issue by bigman212** [MetaMask/metamask-android-sdk#47]
## Steps to reproduce in sample app: 
1) Connect Metamask wallet using SDK
2) Close the app
3) Modify the code so the ACTIONS screen appears first and launch
4) Press `Sign Message` 
4) App crashes with StackOveflow and infinite cycle of
```
at io.metamask.androidsdk.Ethereum.requestAccounts(Ethereum.kt:129)
    at io.metamask.androidsdk.Ethereum.sendRequest(Ethereum.kt:150)
    at io.metamask.androidsdk.Ethereum.requestAccounts(Ethereum.kt:129)
    at io.metamask.androidsdk.Ethereum.sendRequest(Ethereum.kt:150)
    at io.metamask.androidsdk.Ethereum.requestAccounts(Ethereum.kt:129)
    at io.metamask.androidsdk.Ethereum.sendRequest(Ethereum.kt:150)
    at io.metamask.androidsdk.Ethereum.requestAccounts(Ethereum.kt:129)
    at io.metamask.androidsdk.Ethereum.sendRequest(Ethereum.kt:150)
    at io.metamask.androidsdk.Ethereum.requestAccounts(Ethereum.kt:129)
......
``` 
## Expected result
The SDK doesn't crash and Sign Message flow is finished without any errors.

## Probable cause
Infinite cycle and crash is caused by io/metamask/androidsdk/Ethereum.kt:149
```kotlin
        if (!connectRequestSent) {
            requestAccounts {
                sendRequest(request, callback)
            }
            return
        }
```
`connectRequestSent` is always false and doesn't change value until you call `connect`. But I don't need to do that again - the connection and session was established in step 1

@elefantel @andreahaku

**Comment by elefantel** [comment]
Thanks for this feedback. Please see explanation on #48 . You don't need to tag us otherwise, we check the issues regularly :)

**Comment by christopherferreira9** [comment]
Hi @bigman212 we're going to close this issue, please refere to the [mobile issue](https://github.com/MetaMask/metamask-mobile/issues/7525) to check its status.
